# repo.py
from pymongo import AsyncMongoClient
from bson import ObjectId

import os
from dotenv import load_dotenv
from pymongo import MongoClient, ReturnDocument

load_dotenv()  # Load environment variables from .env file
uri = os.getenv("MONGO_URL")
db_name = os.getenv("MONGODB_DB")


class repo():
    def __init__(self):
        # This initializes the driver, but doesn't create anything on the server yet
        self.client = AsyncMongoClient(uri)
        self.db = self.client[db_name]
        self.collection = self.db["users"]

    async def getAllUsers(self):    
        cursor = self.collection.find({})
        # Return the list directly! Pydantic will handle the mapping automatically
        return await cursor.to_list(length=100)
    
    async def addUser(self,username,fname, lname, email, passwd):
        new_user = {
            "_id": username, # ensures that the username is unique in the collection, and _id is not randomly generated by MongoDB
            "fname": fname,
            "lname": lname,
            "email": email,
            "password": passwd
        }
        # If there is no database created yet, this will create it, and the new user
        await self.collection.insert_one(new_user)
        return new_user
    
        
    async def delUser(self, username):
        deleted_user = await self.collection.find_one_and_delete({"_id": username})
        return deleted_user # No more .pop() needed here!